apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims

spec:
  replicas: 3
  selector:
    matchLabels:
      app: ims
  template:
    metadata:
      labels:
        app: ims

    spec:
      containers:
        - name: ims
          image: jp.icr.io/ns-ims/ims
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP