apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdv

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdv
  template:
    metadata:
      labels:
        app: pdv

    spec:
      containers:
        - name: pdv
          image: jp.icr.io/ns-hb/pdv
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
              